### ISSUE TITLE
NON_PERSISTENT deployment type giving AttributeError

### ISSUE THREAD

**Issue by anandsriraman** [microsoft/DeepSpeed-MII#210]
I'm trying the bloom560m deployment example using 

```
deployment_type=mii.constants.DeploymentType.NON_PERSISTENT
```

However, this results in an AttributeError. Looks like https://github.com/microsoft/DeepSpeed-MII/pull/197 has been merged, but the release hasn't been created yet in Pypy. So installing the package with

```
pip install deepspeed-mii
```

results in version 0.0.4 being installed which was released in Dec 2022.

**Comment by mrwyattii** [comment]
Hi @anandsriraman you are right, it's been a long time since we have done a release. I will talk with the team about pushing out a 0.0.5 release this week. However, we are currently making lots of changes and adding a ton of new features to MII and plan to do a 0.1.0 release with all of those soon!

In the meantime, you can install with `pip install git+https://github.com/microsoft/deepspeed-mii` to get the latest changes

**Comment by mrwyattii** [comment]
0.0.5 and 0.0.6 have been released and include the non-persistent deployment type. Closing this issue
