### ISSUE TITLE
Time to First Token almost same as vllm for large prompts

### ISSUE THREAD

**Issue by idealover** [microsoft/DeepSpeed-MII#257]
Hi, I read the blog post of deepspeed-fastgen and since you are implementing dynamic splitfuse - time to first token (TTFT) should be (much?) lower than vllm on large prompt sizes (I am testing on a prompt of 1.2k tokens). I tried on L4 and A100 80 GPUs with Llama 2 7b chat model and the TTFT is almost the same. Even if I try to send queries using multiple clients to deepspeed server - the TTFT for each of the separate clients is also the same. I was wondering if there was some other option I needed to enable to see the benefits of dynamic splitfuse? I used the following to start the server:
`import mii
mii.serve("meta-llama/Llama-2-7b-hf")`

And the clients are created as in the examples:
`client = mii.client("meta-llama/Llama-2-7b-hf")` 

Values of TTFT on L4s:

vllm: 440ms 
deepspeed-fastgen: 450ms 

On A100 80GB PCle:

vllm: 130ms 
deepspeed-fastgen: 140ms 

Pytorch version: 2.1.0 and CUDA 12.3

**Comment by cmikeh2** [comment]
Time to first token should actually be slightly worse with Dynamic SplitFuse. The primary reason for this is that vLLM will preempt the ongoing generation in order to run prompts as they arrive and add them to the running batch. So at sequence arrival, it will run the full prompt and generate that first token for the sequence immediately. This is the ideal manner to minimize TTFT and generally can't be improved upon (beyond better kernel utilization optimizations).

Where Dynamic SplitFuse improves performance is on generation. In vLLM, when it's processing that prompt (on L4 for instance), there will be a 450 ms (+ generation latency) window in which none of the other clients being served by the system will see any tokens at all, since generative sequences aren't placed into the same batch as a prompt. DeepSpeed Fast-Gen will generate ~2 tokens for all clients while that prompt is being processed on the other hand. Another way to think of it is that in vLLM, each client will experience the TTFT latency for every other client in the system, whereas in Fast-Gen the arrival of a prompt has a much smaller impact on the other running sequences.

**Comment by idealover** [comment]
@cmikeh2 What you said makes sense - so when I read [here](https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-fastgen#b-dynamic-splitfuse-) about dynamic splitfuse - I thought that since the large prompts are split into much smaller chunks; TTFT will be lower than vllm for a batch_size of 1. Thanks for the clarification anyways. Closing the issue
