### ISSUE TITLE
Questions about token throughput about dynamic splitfuse

### ISSUE THREAD

**Issue by ChuanhongLi** [microsoft/DeepSpeed-MII#313]
Thanks for the great work! I use run_benchmark_client.sh(https://github.com/microsoft/DeepSpeedExamples/blob/master/benchmarks/inference/mii/run_benchmark_client.sh)  to test the deepspeed-fastgen performance, and I have add some codes to count actual decoding speed: 
```
# postprocess_results.py->get_summary
average_tokens_per_sec = mean([(len(r.generated_tokens)) / (r.end_time - r.start_time) for r in response_details])
```
As the client num increases, the average decoding speed decreases.  Llama-2-7b and Llama-2-13b show the similar trend.  
![image](https://github.com/microsoft/DeepSpeed-MII/assets/90491543/93498bff-bc7b-4946-85c4-b227885a16b9)

I use prompt length = 2600 and max new token = 60；
When prompt length = 1200 and max new token = 128，I get similar results. 

When request  throughput is improved, but  average decoding speed becomes worse?  

The GPU used is 4090.

**Comment by tohtana** [comment]
Hi @ChuanhongLi,
There are two reasons that the average token throughput decreases as we increase the number of clients.

- If the number of clients is 1 for example, the forward passes always process 1 token for each token generation. The GPU utilization is low but the time for each forward pass is very short. When you increase the number of clients, DS-FastGan combine more token generation with prompt processing. This increases the GPU utilization but the time for a forward pass drastically increases. 
- If you increase the number of clients and it reaches the system's limit (around 2.0 qps in your table), the requests simply waits in the queue. If you double the number of clients, the latency is also double.

Due to the second reason, there is no benefit to receive frequent requests beyond a certain point from users' perspective. In that case, we may need to consider distributing requests to multiple replicas.
