### ISSUE TITLE
[NEED HELP] Quantization inference

### ISSUE THREAD

**Issue by freQuensy23-coder** [microsoft/DeepSpeed-MII#440]
In your presentation I see, that deepspeed can support inference of quantizationed models.  But i  have't found any references or examples in documentation.

Are this feature avalibale now (for mixtral model). Where can i find documentation for this feature.

**Comment by xiaoxiawu-microsoft** [comment]
Hi @freQuensy23-coder 

This is the due to the fact that we can only take FP16 input not BF16.  What you can do is to convert the model to FP16 first with the following code: 

```
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_id = "mistralai/Mixtral-8x7B-v0.1"
save_path = f"fp16_cpu/{model_id}"
model = AutoModelForCausalLM.from_pretrained(model_id)
model = model.to(torch.float16)
tokenizer = AutoTokenizer.from_pretrained(model_id)
model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)
```
Then passed to MII. 

Note that FP6 is only supported for dense layer not sparse MOE. So you won't be able to fit the model in one GPU. Since FP6 only apply to QKVO, not MLP part, there won't be two much acceleration compared to origin mixtral.  

We are trying to develop of the Sparse MoE GeMM for FP6, this will take some time.

**Comment by xiaoxiawu-microsoft** [comment]
close for now, happy to reopen if needed :)
