### ISSUE TITLE
Deactivate quantization?

### ISSUE THREAD

**Issue by remi86** [microsoft/DeepSpeed-MII#91]
Hello,

I've been playing around with the SD image generation. I am seeing the 1.8x speedup (which is awesome), but I've also noticed a small drop in quality. How would I go about to deactivate quantization to see whether that's the reason for the drop?
Thanks

**Comment by mrwyattii** [comment]
@remi86 I realize this issue is old now. SD support has changed a bit since you opened this issue. I just tested the [example](https://github.com/microsoft/DeepSpeed-MII/blob/main/examples/local/txt2img-example.py) we have and noticed that MII was doing a few things wrong with respect to how we initialize DeepSpeed-Inference for Stable Diffusion models. I've updated that in #229 if you want to give it a try. You can now enable/disable kernel injection / CUDA Graph support and change the data type in your `mii_config` dict.

Please reopen this issue if this does not resolve your problem. #229 should be merged into `main` shortly. Thanks!
